import { StyleSheet } from "react-native";

export const getStyles = (isDark, C) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: C.bg },
    statsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 16,
      marginBottom: 16,
    },
    subtitle: { fontSize: 13, color: C.textMuted },
    statsCircle: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: C.card,
      borderWidth: 1,
      borderColor: C.border,
      alignItems: "center",
      justifyContent: "center",
    },
    statsNum: { fontSize: 17, fontWeight: "700", color: C.text },
    statsLabel: { fontSize: 9, color: C.textMuted, letterSpacing: 0.5 },
    inputCard: {
      marginHorizontal: 16,
      marginBottom: 16,
      backgroundColor: C.card,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: C.border,
      paddingTop: 14,
      paddingHorizontal: 14,
      paddingBottom: 12,
    },
    input: {
      fontSize: 15,
      color: C.text,
      paddingVertical: 4,
      marginBottom: 10,
    },
    inputBottom: { flexDirection: "row", alignItems: "center", gap: 8 },
    addBtn: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    addBtnText: {
      color: "#fff",
      fontSize: 22,
      fontWeight: "300",
      lineHeight: 24,
    },
    datePill: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: C.border,
      backgroundColor: isDark ? "#2A2A42" : "#F0EBE3",
    },
    datePillText: { fontSize: 12, fontWeight: "600" },
    pickerCard: {
      marginHorizontal: 16,
      marginBottom: 12,
      backgroundColor: C.card,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: C.border,
      padding: 12,
    },
    pickerBtns: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 10,
      marginTop: 8,
    },
    pickerCancel: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 10,
      backgroundColor: isDark ? "#2A2A42" : "#F0EBE3",
    },
    pickerConfirm: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 10,
    },
    catPill: {
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    catPillText: { fontSize: 12, fontWeight: "600", letterSpacing: 0.2 },
    filterRow: {
      flexDirection: "row",
      marginHorizontal: 16,
      marginBottom: 12,
      backgroundColor: isDark ? "#18182A" : "#EDE8E0",
      borderRadius: 14,
      padding: 3,
    },
    filterTab: {
      flex: 1,
      paddingVertical: 8,
      borderRadius: 11,
      alignItems: "center",
    },
    filterTabActive: { backgroundColor: C.card },
    filterTabText: { fontSize: 13, color: C.textMuted, fontWeight: "500" },
    filterTabTextActive: { color: C.text, fontWeight: "600" },
    todoCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: C.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: C.border,
      marginBottom: 8,
      padding: 14,
      overflow: "hidden",
    },
    overdueCard: {
      borderColor: "#EF444444",
      backgroundColor: isDark ? "#2A1818" : "#FFF5F5",
    },
    catStripe: { position: "absolute", left: 0, top: 0, bottom: 0, width: 3 },
    catDot: { width: 12, height: 12, borderRadius: 6, flexShrink: 0 },
    checkbox: {
      width: 22,
      height: 22,
      borderRadius: 7,
      borderWidth: 2,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    todoText: { fontSize: 15, color: C.text, fontWeight: "400" },
    done: { textDecorationLine: "line-through", color: C.textMuted },
    catLabel: { fontSize: 11, fontWeight: "600", letterSpacing: 0.3 },
    dateLabel: { fontSize: 11, fontWeight: "500" },
    deleteAction: {
      backgroundColor: "#EF4444",
      justifyContent: "center",
      alignItems: "center",
      width: 90,
      marginBottom: 8,
      borderRadius: 14,
    },
    deleteActionText: { color: "#fff", fontSize: 13, fontWeight: "600" },
    emptyBox: { alignItems: "center", marginTop: 60 },
    emptyIcon: { fontSize: 32, color: C.textMuted, marginBottom: 10 },
    emptyText: { fontSize: 14, color: C.textMuted },
    detailLabel: {
      fontSize: 12,
      fontWeight: "600",
      color: C.textMuted,
      letterSpacing: 0.5,
      textTransform: "uppercase",
      marginBottom: 8,
      marginTop: 20,
    },
    detailInput: {
      backgroundColor: C.card,
      borderRadius: 14,
      padding: 14,
      fontSize: 16,
      color: C.text,
      borderWidth: 1,
      borderColor: C.border,
      minHeight: 80,
      textAlignVertical: "top",
    },
    statusBadge: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 12,
      alignSelf: "flex-start",
    },
    saveBtn: {
      padding: 16,
      borderRadius: 16,
      alignItems: "center",
      marginBottom: 12,
    },
    saveBtnText: { color: "#fff", fontSize: 16, fontWeight: "700" },
    deleteBtn: {
      padding: 16,
      borderRadius: 16,
      alignItems: "center",
      backgroundColor: isDark ? "#2A1818" : "#FFF5F5",
      borderWidth: 1,
      borderColor: "#EF444444",
    },
    deleteBtnText: { color: "#EF4444", fontSize: 15, fontWeight: "600" },
  });
